spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: embedded

  h2:
    console:
      enabled: false

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
